# SPDX-FileCopyrightText: 2023 Ivan Vilata-i-Balaguer <ivan@selidor.net>
#
# SPDX-License-Identifier: CC0-1.0

# Minimal configuration according to:
# <https://blog.readthedocs.com/migrate-configuration-v2/>.

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py
